#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    GoToFirst,
    GoToLast,
    EnterDirectory,
    GoBack,
    GoToParent,
    GoToRoot,
    GoHome,
    ToggleLabels,
    ToggleHidden,
    RevealInFileManager,
    StartSearch,
    SearchAppend(char),
    SearchBackspace,
    SearchCommit,
    SearchCancel,
}
